project_id = "gyzusnaidbvoxfrqzbig"

[functions.getMessage]
verify_jwt = false

[functions.sendMessage]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.updateApiKey]
verify_jwt = true